# Generated by Django 5.2.5 on 2025-08-26 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('courses', '0005_course_blocked_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
            preserve_default=False,
        ),
    ]
