# Generated by Django 5.2.5 on 2025-08-26 09:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_coursematerial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='blocked_students',
            field=models.ManyToManyField(blank=True, related_name='blocked_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
